### ISSUE TITLE
Beyond Controlled Environments: 3D Camera Re-Localization in Changing Indoor Scenes Availability

### ISSUE THREAD

**Issue by alexs7** [tsattler/MultiCameraPose#1]
Hello,

Is the paper _Beyond Controlled Environments: 3D Camera Re-Localization in Changing Indoor Scenes_ available as pdf ?

Thanks

**Comment by tsattler** [comment]
Hello,

no, not yet. The camera ready deadline for ECCV is Friday, July 17th. We plan to make the paper available on arXiv after the deadline.

Best regards,
Torsten
