### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by Limiao813** [tsattler/MultiCameraPose#4]
Hello, I am sorry, it is not a issues.
I am a novice, I have finished reading your paper, and now I want to quickly run through your code to verify my understanding of your paper.Please teach me how to run your code. For example, file''images_with_intrinsics'' in the code, how to get it?
Thank you very much.

**Comment by tsattler** [comment]
I am sorry for not having found time yet to write a proper documentation. 

There are two executables that you can run `fixed_rig_camera_pose` and `multi_camera_pose`. The former assumes that the absolute scale of the transformation between the images is known while the later estimates it. For both executables, you can define the number of images that are simultaneously localized (modeled as a generalized camera) via a command line parameter. However, the two programs behave a bit differently. If you have 3 cameras in your sequence, then `fixed_rig_camera_pose` jointly localizes images 1, 2, and 3, then jointly localizes images 4, 5, 6 and so on. In contrast, `multi_camera_pose`, for the same sequence length, attempts to jointly localize 1, 2, and 3, then 2, 3, and 4, then 3, 4, and 5, and so on. 

Simply calling one of the programs without parameters will give you a list of command line arguments.

You will need to create the file `images_with_intrinsics` yourself, based on the dataset you are using. You can find the file format in the `common.h` file.

**Comment by tsattler** [comment]
I added details on the input. If there are still problems or questions, please re-open the issue.
