### ISSUE TITLE
Suggestion about the usage

### ISSUE THREAD

**Issue by zjhthu** [tsattler/MultiCameraPose#6]
Hi Prof. Torsten Sattler,
    I am trying to use this project for visual localization, but I find using more images does not provide better results.
    2~5 images are used whose relative poses are given by ARKit. 
    If I understand it correctly, the `images_with_intrinsics` file should provide the rotation (world to camera) and camera center of each query image, the `match_file` provides raw 2d-3d matches for each query. `invert_Y_Z` should be set to `False` and `points_centered` should be set to `False`. 
    So, do you have any idea where I might be wrong? @tsattler

**Comment by tsattler** [comment]
Yes, the rotation matrix transforms from world to camera coordinates and the input vector is the camera center in world coordinates. `invert_Y_Z` should be set to false (0) if you are using the standard computer vision coordinate system and `points_centered` should be set to false (0) if your keypoints are not already centered around the principal points of the images.

The algorithm used for pose estimation requires that the relative poses between the images making up the multi-camera system are very precise. If your poses are estimated using SLAM / VO, then there naturally is drift in the pose estimates. As such, using more images does not help improve performance. It actually hurts performance as it becomes less likely that matches are sampled from nearby images inside RANSAC.

**Comment by zjhthu** [comment]
thanks, I will check whether the relative poses are good enough

**Comment by zjhthu** [comment]
Hi Prof,
    To what extent can the gpnp solver tolerate the errors in the relative pose? 
     As shown in the Table 6 of your paper `Benchmarking 6DOF Outdoor Visual Localization in Changing Conditions`, using poses from a multi-camera VO system also helps a lot. Will 2° be too high for the gpnp solver?

**Comment by tsattler** [comment]
I do not know. I never evaluated the impact of pose errors on the performance of the solver in detail.

**Comment by zjhthu** [comment]
ok, still thanks a lot!

**Comment by alexs7** [comment]
@tsattler you do not recommend using this approach for ARkit (or other similar systems) ? I am looking at also leveraging multiple frames coming from one camera to improve offline localization, but most literature I came across refers to multiple camera systems.

**Comment by tsattler** [comment]
I am not making any recommendation. I am just saying that generalized absolute pose estimation is sensitive to pose accuracy.
