### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by ericzzj1989** [tsattler/MultiCameraPose#7]
Hello, I am sorry to ask how to compile this repository.

I have downloaded and compiled the dependency [Poselib](https://github.com/ericzzj1989/PoseLib) and modified the FindPoseLib.cmake file. However, there still exists an error about nonexistent of PoseLib.

Could you please provide some information about compilation of this project?
PS: I am not clear about the  2D-3D matches file configuration and I wonder how to get such text file. How about running Colmap or something else?

Many thanks and look forward to hearing from you.

**Comment by tsattler** [comment]
I added information to the README. Please let me know if there are still questions.

You can create the 2D-3D matches in any ways you see fit. The best way will of course depend on your setup.

**Comment by ericzzj1989** [comment]
Thanks for your explanation.
Just a typo in the README.md, 'images_with_extrinsics' in the 'outfile' should be 'images_with_intrinsics' since there is no 'images_with_extrinsics' parameter.

**Comment by tsattler** [comment]
Thanks for catching the type.
